FROM golang:latest
MAINTAINER M.K. Mounir <m.khanouri@live.fr>

# Copy the local package files to the container’s workspace.
ADD . /go/src/github.com/MounirOnGithub/go-rest-service

# Dependencies
RUN go get github.com/urfave/negroni
RUN go get github.com/urfave/cli
RUN go get github.com/meatballhat/negroni-logrus
RUN go get github.com/gorilla/mux
RUN go get github.com/Sirupsen/logrus
RUN go get github.com/dgrijalva/jwt-go
RUN go get github.com/asaskevich/govalidator
RUN go get github.com/satori/go.uuid
RUN go get gopkg.in/mgo.v2
RUN go get gopkg.in/mgo.v2/bson

# Install api binary globally within container 
RUN go install github.com/MounirOnGithub/go-rest-service

# Set binary as entrypoint
ENTRYPOINT /go/bin/go-rest-service

# Expose default port (3000)
EXPOSE 3000 